// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations.OfferCacheDb
{
    [DbContext(typeof(OfferCacheDbContext))]
    [Migration("20260715151738_OfferCacheDbMigration-v1")]
    partial class OfferCacheDbMigrationv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DataAccess.OfferCacheRow", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OffersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RestaurantId");

                    b.ToTable("OfferCache", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
